services:
    resume-site:
      build: . 
      image: ${DOCKER_USER}/github-actions-app:${DOCKER_TAG}
      container_name: birender_resume
      ports:
        - 8080:80
      restart: always
      networks: 
            - resume-net
networks:
    resume-net:
      
